### ISSUE TITLE
使用 Cmake 方式 , 未找到对应的 so 文件

### ISSUE THREAD

**Issue by ALuoBo** [xiaozhuang799/Study-Android-SerialPort-Api#1]
按照您的教程，完成所有步骤之后，没有生成 .so 文件，请问是否正常。在您的库中也没有找到。
![image](https://user-images.githubusercontent.com/45779049/169768202-0397bc4a-21a2-47f2-a6f9-90562836ab20.png)

**Comment by xiaozhuang799** [comment]
so文件会自动打包进apk的，你可以解压apk后查看so文件。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ALuoBo ***@***.***&gt;
发送时间: 2022年5月23日 15:41
收件人: xiaozhuang799/Study-Android-SerialPort-Api ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [xiaozhuang799/Study-Android-SerialPort-Api] 使用 Cmake 方式 , 未找到对应的 so 文件 (Issue #1)





 
按照您的教程，完成所有步骤之后，没有生成 .so 文件，请问是否正常。在您的库中也没有找到。
